{ version: '1.2.0',
  events:
   { ADD_SERVERS: 'add_servers',
     REMOVE_SERVERS: 'remove_servers',
     REPLACE_SERVERS: 'replace_servers',
     BIND_SESSION: 'bind_session',
     UNBIND_SESSION: 'unbind_session',
     CLOSE_SESSION: 'close_session',
     ADD_CRONS: 'add_crons',
     REMOVE_CRONS: 'remove_crons',
     START_SERVER: 'start_server',
     START_ALL: 'start_all' },
  components:
   { backendSession: [Getter],
     channel: [Getter],
     connection: [Getter],
     connector: [Getter],
     dictionary: [Getter],
     master: [Getter],
     monitor: [Getter],
     protobuf: [Getter],
     proxy: [Getter],
     pushScheduler: [Getter],
     remote: [Getter],
     server: [Getter],
     session: [Getter] },
  filters:
   { serial: [Getter],
     time: [Getter],
     timeout: [Getter],
     toobusy: [Getter] },
  rpcFilters: { rpcLog: [Getter], toobusy: [Getter] },
  connectors:
   { sioconnector: [Getter],
     hybridconnector: [Getter],
     udpconnector: [Getter],
     mqttconnector: [Getter] },
  pushSchedulers: { direct: [Getter], buffer: [Getter] },
  createApp: [Function],
  backendSession: [Getter],
  channel: [Getter],
  connection: [Getter],
  connector: [Getter],
  dictionary: [Getter],
  master: [Getter],
  monitor: [Getter],
  protobuf: [Getter],
  proxy: [Getter],
  pushScheduler: [Getter],
  remote: [Getter],
  server: [Getter],
  session: [Getter],
  serial: [Getter],
  time: [Getter],
  timeout: [Getter],
  toobusy: [Getter] }